Lesson 4 Homework
CookieFog/aqa_course_HW pull request #2
Opened 2024-03-10 10:16 UTC by CookieFog

2024-03-10 15:27 UTC, dyakov22 requested changes

2024-03-10 15:27 UTC, dyakov22 commented on Homework_4.py
> +list_2.append(Name_marianna.capitalize())
давай зробисо через цикл або лист компрехеншн

2024-03-10 15:27 UTC, dyakov22 commented on Homework_4.py
> +print(list_3)
те ж саме, треба було виконати це завдання за рахунок методів рядка, а не просто присвоїти нові значення по індексу
ще додам про снейк кейс, це коли усі літери маленькими та замість пробів ставиться _
можешь подивитись у перщому занятті презентацію

2024-03-10 15:27 UTC, dyakov22 commented on Homework_4.py
> +if 'PHP' and 'Python' and 'C++' and 'C#' in dictionary_1:
навіщо тут іф? 
якщо я додам нову мову то цей код вже нічого не запринтить 
та давай знову ж таки через цикл зробимо

2024-03-10 15:27 UTC, dyakov22 commented on Homework_4.py
> +for names in ['Jack', 'Leon', 'Alice', 'Bob']:
треба було зробити за допомогою isinstance або метода type()

2024-03-10 15:27 UTC, dyakov22 commented on Homework_4.py
> +    if (isinstance(types[0], int) and isinstance(types[1], int)
навіщо ти перевіряєшь усі типи по індексах коли цикл створенний для того щоб ітеруватись то послідовностях (тобто проходитись по кожному елементу у послідовностях)

2024-03-10 15:27 UTC, dyakov22 commented on Homework_4.py
> +        value += 1
якщо я хочу додати нуль до 10 то не зможу цього зробити через цю умову

2024-03-12 10:22 UTC, CookieFog commented on Homework_4.py
> +list_2.append(Name_marianna.capitalize())
Done!

2024-03-12 10:47 UTC, CookieFog commented on Homework_4.py
> +if 'PHP' and 'Python' and 'C++' and 'C#' in dictionary_1:
Done!

2024-03-12 12:00 UTC, CookieFog commented on Homework_4.py
> +        value += 1
Done!

2024-03-12 14:00 UTC, CookieFog commented on Homework_4.py
> +print(list_3)
done

2024-03-12 14:00 UTC, CookieFog commented on Homework_4.py
> +    if (isinstance(types[0], int) and isinstance(types[1], int)
done

2024-03-12 14:00 UTC, CookieFog commented on Homework_4.py
> +for names in ['Jack', 'Leon', 'Alice', 'Bob']:
done

2024-03-12 14:10 UTC, dyakov22 requested changes

2024-03-12 14:10 UTC, dyakov22 commented on Homework_4.py
> +dict_result[x] = dict_result.get(x, 0) + 1
ти впевнений у цьому коді?)

2024-03-12 14:10 UTC, dyakov22 commented on Homework_4.py
> +''.join([f'{key},{value}' for key, value in dict_result.items()])
нагадує мем (тільки не копіюй точ в точ) 

це потрібно було принтити або створити нову змінну

2024-03-12 14:10 UTC, dyakov22 commented on Homework_4.py
> +while value < 2:
немає перевірки на вихід

2024-03-12 14:10 UTC, dyakov22 commented on Homework_4.py
> +            break
навіщо ти закінчуєш цикл після успішнії операції
що робити якщо в мене залишилась ще одна спроба і я хочу виконати додаткову операцію

2024-03-12 14:10 UTC, dyakov22 commented on Homework_4.py
> +        value += 1
замість додавання усюди += 1 міг написати цей вираз у finally

2024-03-12 14:10 UTC, dyakov22 commented on Homework_4.py
> +        print("loop 'For' is not working with float. This program working only with int! ")
додай інформацію про тип даних з котрим не працює цей цикл 
замість флоат (як мінімум в тебе буде дікт а не флоат

2024-03-12 14:19 UTC, CookieFog commented on Homework_4.py
> +            break
убрал break

2024-03-12 14:22 UTC, CookieFog commented on Homework_4.py
> +        value += 1
finally добавил

2024-03-12 14:28 UTC, CookieFog commented on Homework_4.py
> +while value < 2:
какой проверки ?

2024-03-12 14:29 UTC, CookieFog commented on Homework_4.py
> +while value < 2:
вы наверное перепутали с 5 ты дз где должен быть выход

2024-03-12 14:34 UTC, dyakov22 commented on Homework_4.py
> +while value < 2:
так 
все вірно то я вже

2024-03-18 17:27 UTC, merged