Lesson 5
CookieFog/aqa_course_HW pull request #3
Opened 2024-03-10 14:25 UTC by CookieFog

Lesson_HW_5 is done !

2024-03-10 15:58 UTC, dyakov22 requested changes

2024-03-10 15:58 UTC, dyakov22 commented on Lesson_5.py
> +class SqrtError(Exception):
в тебе вже є створена помилка 
другий раз її не потрібно створювати

2024-03-10 15:58 UTC, dyakov22 commented on Lesson_5.py
> +        First_number = float(input("Please enter first number for calculation process"))
змінні називаються з маленької

2024-03-10 15:58 UTC, dyakov22 commented on Lesson_5.py
> +value = 1
повинно починатись з нуля 
тому що так ти даєшь тільки одну спробу
та де ти додаєшь до цієї змінної 1 коли спроба була успішна, в такій реалізації в тебе буде нескінчений калькулятор до моменту вводу Exit (та з приводу слова, краще використовувати лоувер кейс

2024-03-10 15:58 UTC, dyakov22 commented on Lesson_5.py
> +    if reboot_calculation == 'F':
тут не потрібно запитувати про іншу спробу 
тут потрібно додавати до каунтера 1

2024-03-10 16:06 UTC, CookieFog commented on Lesson_5.py
> +        First_number = float(input("Please enter first number for calculation process"))
done!

2024-03-10 16:09 UTC, CookieFog commented on Lesson_5.py
> +class SqrtError(Exception):
done!

2024-03-10 16:25 UTC, CookieFog commented on Lesson_5.py
> +value = 1
done !

2024-03-12 14:37 UTC, dyakov22 requested changes

2024-03-12 14:37 UTC, dyakov22 commented on Lesson_5.py
> +while value < 2:
навіщо тут цикл та 2 спроби?

2024-03-12 14:37 UTC, dyakov22 commented on Lesson_5.py
> +            value += 1
відносить до 2 спроб
воно не потрібно у рамках цього завдання

2024-03-12 15:01 UTC, merged