Lesson 8
CookieFog/aqa_course_HW pull request #6
Opened 2024-03-20 03:16 UTC by CookieFog

2024-03-20 09:08 UTC, dyakov22 requested changes

2024-03-20 09:08 UTC, dyakov22 commented on Homework_8.py
> +    with open('C:/Users/user/Desktop/test_file.csv', mode='w') as file:
зроби так щоб шлях щука вся динамічно а не був статичним

2024-03-20 09:08 UTC, dyakov22 commented on Homework_8.py
> +        salary_1 = 1000  # $
тобі потрібно було прочитати файл та з цими даними вже працювати 
а не захардкодити селері
і в кінці створити новій файл з результатом

2024-03-20 09:23 UTC, CookieFog commented on Homework_8.py
> +    with open('C:/Users/user/Desktop/test_file.csv', mode='w') as file:
а это как ? :D

2024-03-20 10:27 UTC, CookieFog commented on Homework_8.py
> +        salary_1 = 1000  # $
можете подсказать как создать файл CSV формата через питон

2024-03-25 09:09 UTC, dyakov22 commented
подивись на цей код, як розбереш то пиши усі питання у особисті


import csv


currency_exchange_rate = 39

with open('test_file.csv', mode='r') as file:
    csv_reader = csv.reader(file)
    users_salaries = list(csv_reader)
    months = users_salaries[0]
    salaries_uah = []

    for row in users_salaries[1:]:
        employee = row[0]
        salaries = [int(salary) * currency_exchange_rate for salary in row[1:]]
        salaries.insert(0, employee)
        salaries_uah.append(salaries)

with open('salaries_uah.csv', mode='w') as file:
    csv_writer = csv.writer(file)
    csv_writer.writerow(months)
    csv_writer.writerows(salaries_uah)

2024-04-11 09:41 UTC, merged